server:
  port: 9296
spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mauly1/config-server
          clone-on-start: true